RUN_REGISTRY_RUN_355556_DATA = {
    "run_number": 355556,
    "oms_attributes": {
        "energy": 450,
        "l1_key": "l1_trg_circulating2022/v34",
        "b_field": 3.8,
        "hlt_key": "/cdaq/circulating/2022/v3.4/HLT/V3",
        "l1_menu": "L1Menu_Collisions2022_v1_2_0",
        "l1_rate": 517.358,
        "duration": 5094,
        "end_lumi": 0,
        "end_time": "2022-07-12T22:47:40Z",
        "sequence": "GLOBAL-RUN",
        "init_lumi": 0,
        "clock_type": "LHC",
        "components": [
            "CSC",
            "CTPPS",
            "CTPPS_TOT",
            "DAQ",
            "DCS",
            "DQM",
            "DT",
            "ECAL",
            "ES",
            "GEM",
            "HCAL",
            "L1SCOUT",
            "PIXEL",
            "RPC",
            "TCDS",
            "TRACKER",
            "TRG",
        ],
        "run_number": 355556,
        "start_time": "2022-07-12T21:22:46Z",
        "dt_included": True,
        "es_included": True,
        "fill_number": 7968,
        "l1_hlt_mode": "circulating2022",
        "last_update": "2022-08-25T10:45:57Z",
        "ls_duration": 226,
        "stable_beam": False,
        "csc_included": True,
        "daq_included": True,
        "dcs_included": True,
        "dqm_included": True,
        "gem_included": True,
        "rpc_included": True,
        "trg_included": True,
        "trigger_mode": "l1_hlt_circulating2022/v67",
        "cmssw_version": "CMSSW_12_3_7",
        "ecal_included": True,
        "hcal_included": True,
        "recorded_lumi": 1.5e-05,
        "tcds_included": True,
        "beta_star_stop": None,
        "components_out": [],
        "ctpps_included": True,
        "delivered_lumi": 1.5e-05,
        "pixel_included": True,
        "tier0_transfer": True,
        "beta_star_start": None,
        "l1_key_stripped": "circulating2022/v34",
        "fill_type_party1": "PROTON",
        "fill_type_party2": "PROTON",
        "hlt_physics_rate": 28.83,
        "hlt_physics_size": 10.431,
        "l1scout_included": True,
        "tracker_included": True,
        "fill_type_runtime": "PROTONS",
        "ctpps_tot_included": True,
        "crossing_angle_stop": None,
        "hlt_physics_counter": 145835,
        "l1_triggers_counter": 2606350,
        "crossing_angle_start": None,
        "l1_hlt_mode_stripped": "circulating2022/v67",
        "hlt_physics_throughput": 0.00206216,
        "initial_prescale_index": 10,
        "last_lumisection_number": 218,
        "beams_present_and_stable": False,
        "beamactive_total_deadtime": 0,
    },
    "rr_attributes": {
        "class": "Commissioning22",
        "state": "SIGNOFF",
        "significant": True,
        "stop_reason": "Beam lost and Inject phyiscs beam again",
        "run_needs_to_be_updated_manually": True,
    },
    "version": 46592999,
    "deleted": False,
    "DatasetTripletCache": {
        "triplet_summary": {
            "dt-dt": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "cms-cms": {"BAD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "csc-csc": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "ecal-es": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "gem-gem": {"BAD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "hlt-hlt": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "l1t-l1t": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "rpc-rpc": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "ecal-ecal": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "hcal-hcal": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "l1t-l1tmu": {"EMPTY": 0, "NOTSET": 226, "causes": [], "comments": []},
            "lumi-lumi": {"GOOD": 226, "EMPTY": 0, "causes": [], "comments": []},
            "ctpps-ctpps": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "l1t-l1tcalo": {"EMPTY": 0, "NOTSET": 226, "causes": [], "comments": []},
            "castor-castor": {
                "EMPTY": 0,
                "causes": [],
                "EXCLUDED": 226,
                "comments": [],
            },
            "tracker-pixel": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "tracker-strip": {"EMPTY": 0, "causes": [], "STANDBY": 226, "comments": []},
            "ctpps-rp45_210": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-rp45_220": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-rp45_cyl": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-rp56_210": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-rp56_220": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-rp56_cyl": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-time45_box": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
            "ctpps-time56_box": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 226,
                "comments": [],
            },
        }
    },
}
{"rr_run_class": "Commissioning22", "rr_significant": False}
RUN_REGISTRY_RUN_355555_DATA = {
    "run_number": 355555,
    "oms_attributes": {
        "energy": 7864,
        "l1_key": "l1_trg_cosmics2022/v84",
        "b_field": 3.8,
        "hlt_key": "/cdaq/cosmic/commissioning2022/CRAFT/v3.4/HLT/V2",
        "l1_menu": "L1Menu_Collisions2022_v1_2_0",
        "l1_rate": 96213.84,
        "duration": 8909,
        "end_lumi": 0,
        "end_time": "2022-07-12T21:18:59Z",
        "sequence": "GLOBAL-RUN",
        "init_lumi": 0,
        "clock_type": "LOCAL",
        "components": [
            "CSC",
            "CTPPS",
            "CTPPS_TOT",
            "DAQ",
            "DCS",
            "DQM",
            "DT",
            "ECAL",
            "ES",
            "GEM",
            "HCAL",
            "L1SCOUT",
            "PIXEL",
            "RPC",
            "TCDS",
            "TRACKER",
            "TRG",
        ],
        "run_number": 355555,
        "start_time": "2022-07-12T18:50:30Z",
        "dt_included": True,
        "es_included": True,
        "fill_number": 7968,
        "l1_hlt_mode": "cosmics2022",
        "last_update": "2022-08-25T10:45:49Z",
        "ls_duration": 392,
        "stable_beam": False,
        "csc_included": True,
        "daq_included": True,
        "dcs_included": True,
        "dqm_included": True,
        "gem_included": True,
        "rpc_included": True,
        "trg_included": True,
        "trigger_mode": "l1_hlt_cosmics2022/v136",
        "cmssw_version": "CMSSW_12_3_7",
        "ecal_included": True,
        "hcal_included": True,
        "recorded_lumi": 0,
        "tcds_included": True,
        "beta_star_stop": None,
        "components_out": [],
        "ctpps_included": True,
        "delivered_lumi": 0,
        "pixel_included": True,
        "tier0_transfer": True,
        "beta_star_start": None,
        "l1_key_stripped": "cosmics2022/v84",
        "fill_type_party1": "PROTON",
        "fill_type_party2": "PROTON",
        "hlt_physics_rate": 204.086,
        "hlt_physics_size": 270.533,
        "l1scout_included": True,
        "tracker_included": True,
        "fill_type_runtime": "COSMICS",
        "ctpps_tot_included": True,
        "crossing_angle_stop": None,
        "hlt_physics_counter": 1807781,
        "l1_triggers_counter": 852241977,
        "crossing_angle_start": None,
        "l1_hlt_mode_stripped": "cosmics2022/v136",
        "hlt_physics_throughput": 0.03054127,
        "initial_prescale_index": 3,
        "last_lumisection_number": 381,
        "beams_present_and_stable": False,
        "beamactive_total_deadtime": 0,
    },
    "rr_attributes": {
        "class": "Cosmics22",
        "state": "SIGNOFF",
        "significant": True,
        "stop_reason": "change to circulating keys as beam mode changed to INJECTION PROBE BEAM\n",
        "run_needs_to_be_updated_manually": True,
    },
    "version": 46592939,
    "deleted": False,
    "DatasetTripletCache": {
        "triplet_summary": {
            "dt-dt": {
                "GOOD": 303,
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 32,
                "comments": [],
            },
            "cms-cms": {"BAD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "csc-csc": {
                "GOOD": 323,
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 12,
                "comments": [],
            },
            "ecal-es": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "gem-gem": {
                "BAD": 32,
                "GOOD": 303,
                "EMPTY": 0,
                "causes": [],
                "comments": [],
            },
            "hlt-hlt": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "l1t-l1t": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "rpc-rpc": {
                "GOOD": 303,
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 32,
                "comments": [],
            },
            "ecal-ecal": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "hcal-hcal": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "l1t-l1tmu": {"EMPTY": 0, "NOTSET": 335, "causes": [], "comments": []},
            "lumi-lumi": {"GOOD": 335, "EMPTY": 0, "causes": [], "comments": []},
            "ctpps-ctpps": {"EMPTY": 0, "causes": [], "STANDBY": 335, "comments": []},
            "l1t-l1tcalo": {"EMPTY": 0, "NOTSET": 335, "causes": [], "comments": []},
            "castor-castor": {
                "EMPTY": 0,
                "causes": [],
                "EXCLUDED": 335,
                "comments": [],
            },
            "tracker-pixel": {
                "GOOD": 304,
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 31,
                "comments": [],
            },
            "tracker-strip": {
                "GOOD": 304,
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 31,
                "comments": [],
            },
            "ctpps-rp45_210": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-rp45_220": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-rp45_cyl": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-rp56_210": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-rp56_220": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-rp56_cyl": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-time45_box": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
            "ctpps-time56_box": {
                "EMPTY": 0,
                "causes": [],
                "STANDBY": 335,
                "comments": [],
            },
        }
    },
}
