kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: cms-hdqm-dev
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: hdqm
    app.openshift.io/runtime: flask
    app.openshift.io/runtime-namespace: cms-hdqm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        deployment: backend
    spec:
      volumes:
        - name: eos-storage
          persistentVolumeClaim:
            claimName: eos-storage
      containers:
        - name: backend
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2048Mi
          command: ['bash']
          args: ['run.sh', 'api']
          envFrom:
            - secretRef:
                name: hdqm-backend-secrets
            - secretRef:
                name: eos-credentials
          imagePullPolicy: Always
          volumeMounts:
            - name: eos-storage
              readOnly: true
              mountPath: /eos
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-hdqm-dev/backend:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
