kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: cms-hdqm-prod
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
    app.openshift.io/runtime-version: latest
spec:
  type: ClusterIP
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: frontend
    deployment: frontend


